/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsShampooRouteImport } from './routes/products/shampoo'
import { Route as ProductsMaharaniRouteImport } from './routes/products/maharani'
import { Route as ProductsIndigoRouteImport } from './routes/products/indigo'
import { Route as ProductsHennaRouteImport } from './routes/products/henna'
import { Route as ProductsAtharvaRouteImport } from './routes/products/atharva'

const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsShampooRoute = ProductsShampooRouteImport.update({
  id: '/products/shampoo',
  path: '/products/shampoo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMaharaniRoute = ProductsMaharaniRouteImport.update({
  id: '/products/maharani',
  path: '/products/maharani',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndigoRoute = ProductsIndigoRouteImport.update({
  id: '/products/indigo',
  path: '/products/indigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHennaRoute = ProductsHennaRouteImport.update({
  id: '/products/henna',
  path: '/products/henna',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAtharvaRoute = ProductsAtharvaRouteImport.update({
  id: '/products/atharva',
  path: '/products/atharva',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company': typeof CompanyRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/products/atharva': typeof ProductsAtharvaRoute
  '/products/henna': typeof ProductsHennaRoute
  '/products/indigo': typeof ProductsIndigoRoute
  '/products/maharani': typeof ProductsMaharaniRoute
  '/products/shampoo': typeof ProductsShampooRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company': typeof CompanyRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/products/atharva': typeof ProductsAtharvaRoute
  '/products/henna': typeof ProductsHennaRoute
  '/products/indigo': typeof ProductsIndigoRoute
  '/products/maharani': typeof ProductsMaharaniRoute
  '/products/shampoo': typeof ProductsShampooRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/company': typeof CompanyRoute
  '/faq': typeof FaqRoute
  '/guide': typeof GuideRoute
  '/products/atharva': typeof ProductsAtharvaRoute
  '/products/henna': typeof ProductsHennaRoute
  '/products/indigo': typeof ProductsIndigoRoute
  '/products/maharani': typeof ProductsMaharaniRoute
  '/products/shampoo': typeof ProductsShampooRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/company'
    | '/faq'
    | '/guide'
    | '/products/atharva'
    | '/products/henna'
    | '/products/indigo'
    | '/products/maharani'
    | '/products/shampoo'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/company'
    | '/faq'
    | '/guide'
    | '/products/atharva'
    | '/products/henna'
    | '/products/indigo'
    | '/products/maharani'
    | '/products/shampoo'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/company'
    | '/faq'
    | '/guide'
    | '/products/atharva'
    | '/products/henna'
    | '/products/indigo'
    | '/products/maharani'
    | '/products/shampoo'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompanyRoute: typeof CompanyRoute
  FaqRoute: typeof FaqRoute
  GuideRoute: typeof GuideRoute
  ProductsAtharvaRoute: typeof ProductsAtharvaRoute
  ProductsHennaRoute: typeof ProductsHennaRoute
  ProductsIndigoRoute: typeof ProductsIndigoRoute
  ProductsMaharaniRoute: typeof ProductsMaharaniRoute
  ProductsShampooRoute: typeof ProductsShampooRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/shampoo': {
      id: '/products/shampoo'
      path: '/products/shampoo'
      fullPath: '/products/shampoo'
      preLoaderRoute: typeof ProductsShampooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/maharani': {
      id: '/products/maharani'
      path: '/products/maharani'
      fullPath: '/products/maharani'
      preLoaderRoute: typeof ProductsMaharaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/indigo': {
      id: '/products/indigo'
      path: '/products/indigo'
      fullPath: '/products/indigo'
      preLoaderRoute: typeof ProductsIndigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/henna': {
      id: '/products/henna'
      path: '/products/henna'
      fullPath: '/products/henna'
      preLoaderRoute: typeof ProductsHennaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/atharva': {
      id: '/products/atharva'
      path: '/products/atharva'
      fullPath: '/products/atharva'
      preLoaderRoute: typeof ProductsAtharvaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompanyRoute: CompanyRoute,
  FaqRoute: FaqRoute,
  GuideRoute: GuideRoute,
  ProductsAtharvaRoute: ProductsAtharvaRoute,
  ProductsHennaRoute: ProductsHennaRoute,
  ProductsIndigoRoute: ProductsIndigoRoute,
  ProductsMaharaniRoute: ProductsMaharaniRoute,
  ProductsShampooRoute: ProductsShampooRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
