import { productImages } from "./product-images";

export type ProductPhotoFrame = {
  left: number;
  top: number;
  width: number;
  height: number;
  imageWidth: number;
  imageHeight: number;
};

// Generated by scripts/measure-product-photos.mjs. Original image bytes remain unchanged.
export const productPhotoFrames: Record<string, ProductPhotoFrame> = Object.fromEntries([
  [
    productImages["マハラニヘナ 石臼挽き"],
    { left: 172, top: 0, width: 359, height: 500, imageWidth: 700, imageHeight: 500 },
  ],
  [
    productImages["マハラニヘナ ファイン粉末"],
    { left: 170, top: 0, width: 361, height: 509, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["マハラニヘナ (機械挽き)"],
    { left: 169, top: 1, width: 362, height: 507, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["オーガニック ヘナコンシーラー"],
    { left: 223, top: 6, width: 126, height: 686, imageWidth: 576, imageHeight: 700 },
  ],
  [
    productImages["インディゴ"],
    { left: 169, top: 0, width: 365, height: 509, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["ハーバルカラー1 ライトブラウン"],
    { left: 169, top: 0, width: 365, height: 509, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["ハーバルカラー3 ブラウン"],
    { left: 169, top: 0, width: 365, height: 509, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["ハーバルカラー5 ダークブラウン"],
    { left: 169, top: 0, width: 365, height: 509, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["ハーバルカラー7 ソフトブラック"],
    { left: 169, top: 0, width: 365, height: 509, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["ハーバルカラー9 ブルーブラック"],
    { left: 169, top: 0, width: 365, height: 509, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["カラートリートメント花ブレンド"],
    { left: 2, top: 3, width: 362, height: 497, imageWidth: 364, imageHeight: 500 },
  ],
  [
    productImages["ハーブシャンプー 香る髪"],
    { left: 0, top: 0, width: 355, height: 500, imageWidth: 355, imageHeight: 500 },
  ],
  [
    productImages["ハーブシャンプー 香る髪プラス"],
    { left: 1, top: 1, width: 358, height: 499, imageWidth: 360, imageHeight: 500 },
  ],
  [
    productImages["ハーブシャンプー 香る髪ベーシック"],
    { left: 0, top: 0, width: 200, height: 276, imageWidth: 200, imageHeight: 276 },
  ],
  [
    productImages["香る髪ラベンダー"],
    { left: 1, top: 0, width: 358, height: 500, imageWidth: 360, imageHeight: 500 },
  ],
  [
    productImages["香る髪アロマプラス"],
    { left: 0, top: 0, width: 200, height: 282, imageWidth: 200, imageHeight: 282 },
  ],
  [
    productImages["香る髪花ブレンド"],
    { left: 1, top: 0, width: 358, height: 500, imageWidth: 360, imageHeight: 500 },
  ],
  [
    productImages["香る髪オレンジ２"],
    { left: 0, top: 0, width: 200, height: 276, imageWidth: 200, imageHeight: 276 },
  ],
  [
    productImages["香る髪ペパーミント"],
    { left: 0, top: 0, width: 181, height: 250, imageWidth: 181, imageHeight: 250 },
  ],
  [
    productImages["香る髪オイリースカルプ"],
    { left: 0, top: 0, width: 200, height: 286, imageWidth: 200, imageHeight: 286 },
  ],
  [
    productImages["ヘナシカ洗髪粉"],
    { left: 0, top: 0, width: 362, height: 500, imageWidth: 362, imageHeight: 500 },
  ],
  [
    productImages["ニュー香る髪"],
    { left: 0, top: 0, width: 200, height: 276, imageWidth: 200, imageHeight: 276 },
  ],
  [
    productImages["カラーレストリートメント (カッシア)"],
    { left: 2, top: 2, width: 429, height: 598, imageWidth: 432, imageHeight: 600 },
  ],
  [
    productImages["カラーレス花ブレンド"],
    { left: 0, top: 0, width: 355, height: 500, imageWidth: 355, imageHeight: 500 },
  ],
  [
    productImages["マハラニ ヘアケアオイル"],
    { left: 0, top: 1, width: 149, height: 499, imageWidth: 149, imageHeight: 500 },
  ],
  [
    productImages["マハラニ ヘアケアオイル FB"],
    { left: 0, top: 0, width: 93, height: 300, imageWidth: 93, imageHeight: 300 },
  ],
  [
    productImages["マハラニ シカカイ"],
    { left: 0, top: 0, width: 181, height: 250, imageWidth: 181, imageHeight: 250 },
  ],
  [
    productImages["マハラニ アムラ"],
    { left: 1, top: 0, width: 359, height: 500, imageWidth: 360, imageHeight: 500 },
  ],
  [
    productImages["マハラニ カチュールスガンディ"],
    { left: 132, top: 0, width: 288, height: 400, imageWidth: 550, imageHeight: 400 },
  ],
  [
    productImages["マハラニ ニーム"],
    { left: 0, top: 0, width: 200, height: 276, imageWidth: 200, imageHeight: 276 },
  ],
  [
    productImages["マハラニ ムルタニミッティ"],
    { left: 0, top: 0, width: 362, height: 500, imageWidth: 362, imageHeight: 500 },
  ],
  [
    productImages["無農薬ローズ粉末"],
    { left: 0, top: 0, width: 355, height: 500, imageWidth: 355, imageHeight: 500 },
  ],
  [
    productImages["アタルバ ヘッドマッサージオイル"],
    { left: 0, top: 7, width: 101, height: 293, imageWidth: 101, imageHeight: 300 },
  ],
  [
    productImages["ヘッドマッサージオイル・リラックス"],
    { left: 2, top: 1, width: 201, height: 599, imageWidth: 204, imageHeight: 600 },
  ],
  [
    productImages["ヘッドマッサージオイル R"],
    { left: 0, top: 10, width: 164, height: 490, imageWidth: 164, imageHeight: 500 },
  ],
  [
    productImages["アタルバ ヘアオイル"],
    { left: 263, top: 1, width: 172, height: 508, imageWidth: 700, imageHeight: 509 },
  ],
  [
    productImages["アタルバ 洗髪粉"],
    { left: 0, top: 0, width: 193, height: 300, imageWidth: 193, imageHeight: 300 },
  ],
  [
    productImages["アタルバ CBLマッサージオイル"],
    { left: 5, top: 13, width: 203, height: 587, imageWidth: 211, imageHeight: 600 },
  ],
  [
    productImages["アタルバ セサミオイル"],
    { left: 0, top: 3, width: 159, height: 497, imageWidth: 159, imageHeight: 500 },
  ],
  [
    productImages["アタルバ ニームオイル"],
    { left: 0, top: 4, width: 159, height: 496, imageWidth: 159, imageHeight: 500 },
  ],
  [
    productImages["アタルバ ベビーオイル"],
    { left: 0, top: 1, width: 162, height: 499, imageWidth: 162, imageHeight: 500 },
  ],
  [
    productImages["マッサージオイル NR"],
    { left: 0, top: 2, width: 163, height: 498, imageWidth: 163, imageHeight: 500 },
  ],
  [
    productImages["ピッタ・マッサージオイル"],
    { left: 0, top: 0, width: 160, height: 500, imageWidth: 160, imageHeight: 500 },
  ],
  [
    productImages["カファ・マッサージオイル"],
    { left: 1, top: 3, width: 161, height: 497, imageWidth: 163, imageHeight: 500 },
  ],
  [
    productImages["ヴァータ・マッサージオイル"],
    { left: 0, top: 0, width: 163, height: 500, imageWidth: 163, imageHeight: 500 },
  ],
  [
    productImages["アタルバ ハーバルスクラブ"],
    { left: 0, top: 0, width: 321, height: 500, imageWidth: 321, imageHeight: 500 },
  ],
  [
    productImages["アタルバ フェイスクリーム R"],
    { left: 0, top: 1, width: 500, height: 409, imageWidth: 500, imageHeight: 410 },
  ],
  [
    productImages["アタルバ フェイスクリーム K"],
    { left: 0, top: 2, width: 500, height: 414, imageWidth: 500, imageHeight: 416 },
  ],
  [
    productImages["アタルバ スキンクリーム"],
    { left: 4, top: 8, width: 581, height: 487, imageWidth: 591, imageHeight: 500 },
  ],
  [
    productImages["アタルバ ハーバルフェイスパック"],
    { left: 0, top: 0, width: 321, height: 500, imageWidth: 321, imageHeight: 500 },
  ],
  [
    productImages["フェイスパック R"],
    { left: 0, top: 0, width: 193, height: 300, imageWidth: 193, imageHeight: 300 },
  ],
  [
    productImages["イェシティマドゥオイル"],
    { left: 0, top: 2, width: 164, height: 498, imageWidth: 164, imageHeight: 500 },
  ],
]);
